# Generated by Django 3.2.3 on 2021-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='product',
            field=models.ManyToManyField(related_query_name='allergy_products', to='products.Product'),
        ),
    ]
