# Generated by Django 3.2.3 on 2021-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_allergy_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='product',
            field=models.ManyToManyField(db_table='allergy_products', to='products.Product'),
        ),
    ]
