# Generated by Django 3.2.3 on 2021-05-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_allergy_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.nutrition'),
        ),
    ]
