# Generated by Django 3.2.3 on 2021-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210523_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='allergy',
            field=models.ManyToManyField(db_table='allergy_products', related_name='allergy_product', to='products.Allergy'),
        ),
    ]
